### ISSUE TITLE
New stub for sequential "topic" page

### ISSUE THREAD

**Issue by patlaj** [neoinsight/start-business#3]
Hey @anniecrombie  - I've added a stub with your link and doormat copy here:

https://neoinsight.github.io/start-business/mvp/start-seq-en.html

Note that I left out the topic image, the socmed icons, what we are doing, and the most requested. Whether those things do make sense sort of depends on the direction we go - at this point, I'm not sure that this is really a topic page, in which case the mandatories don't apply. But we can always tweak later. 

I think you should be able to go in and edit the page easily...one thing we may want to do is have the title and doormat have a hanging indent, so the digit stands alone (like a bullet). That might require a bit more CSS than I can easily manage, so we might need to look into help if we do that. 

Let me know if anything should be adjusted - I'm at home for a bit since it's easier to work on this stuff here.

**Comment by anniecrombie** [comment]
Thanks! 

Yes, I agree re: hanging bullet. 

I think I would like to add a "most requested", even if we don't put in the other topic-page mandatories.  If you are able to create the box and user our existing Most requested items from the Starting a business page, then I can go in (or have Wendy go in) and adjust them once I've finalized what I want the new content to be.

**Comment by patlaj** [comment]
OK it's in there now - hopefully everything works in IE, I had to do some things I don't understand to get the doormats to appear in the right place.

**Comment by patlaj** [comment]
Got the hanging indents...not 100% sure about them but it's easy to switch anyway.
